from console import Display
import time

def show():
    oled = Display()
    oled.clear(0, 1)
    oled.draw_graphic("/img/erni_l.txt", 35, 2)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/erni_s.txt", 45, 20)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/erni_logo.txt", 5, 20)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img//img/github_logo.txt", 35, 0)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/upython_logo.txt", 35, 0)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/python_logo.txt", 45, 20)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/upython_logo_s.txt", 45, 20)
    time.sleep(5)
    oled.clear(0, 1)
    oled.draw_graphic("/img/MSC_logo.txt", 15, 2)
    time.sleep(5)
    oled.clear(0, 1)

show()
